name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup node 
        uses: actions/setup-node@v2 
        with: 
          node-version: '12.x' 

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        #env:
          #ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
         # BRANCH: gh-pages
          #FOLDER: build
          #BUILD_SCRIPT: npm install && npm run build
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
